### ISSUE TITLE
multiple URL

### ISSUE THREAD

**Issue by lean79** [sebbu/iControl-Web#16]
ciao and thanks for your software.
I use it for activate/deactivate my security cams, as they can be "called" with a link passing a certain parameter to let them perform some actions (such as activate the motion sensor, indeed).

somethink like that:
  "contextMenuLabel1": "CAM Off",
  "contextMenuCmd1": "http://link_to_cam/?action=off", 

now, I would like to set them OFF (or ON) all together with the same button. Is there any way to launch more than one URL?
ideally something like that:
  "contextMenuCmd1": "http://link_to_cam1/?action=off", "http://link_to_cam2/?action=off",

thanks!

**Comment by sebbu** [comment]
That is not possible because there will always be cases where it does not work as expected. 

Imagine the call to the first camera works and the call to the second does not. 

Normally a home automation system can handle this with some thing called scenes where you would have presets like "home" or "away"

**Comment by lean79** [comment]
Thank you Sebbu. I will check if it is possible with my system.
Ciao!
