### ISSUE TITLE
Apple watch cannot send url request via 3G network but can do it via wifi at home

### ISSUE THREAD

**Issue by vic1743** [sebbu/iControl-Web#21]
Hello Sebastian..

Your application is fantastic ! Thanks for providing for free and i have succeeded implementing it with my home automation system !! Great job !!! It is so fast and convenient now using the apple Watch !!!

I have an issue: I can trigger events via url requests to my home automation server via the apple Watch while my iPhone is running icontrol connected to my home wifi. However when i switch to 3G network (e.g if im not home) i can't send the commands..
Hello Sebastian..

Your application is fantastic ! Thanks for providing for free and i have succeeded implementing it with my home automation system !! Great job !!! It is so fast and convenient now using the apple Watch !!!

I have an issue: I can trigger events via url requests to my home automation server via the apple Watch while my iPhone is running icontrol connected to my home wifi. However when i switch to 3G network (e.g if im not home) i can't send the commands..

 For your information, I use the following syntax in the JSON file:
http://username:password@dyndnsname:Port No/event. This command works fine from the Watch if im on wifi at home..

However the same command works fine sending it thru safari from my iPhone via 3G 
Dyndns client is ok and port no is open on router and works fine.

Do you have an idea of what it could be ?

Thanks a lot
Vincent

 For your information, I use the following syntax in the JSON file:
http://username:password@dyndnsname:Port No/event. This command works fine from the Watch if im on wifi at home..

However the same command works fine sending it thru safari from my iPhone via 3G 
Dyndns client is ok and port no is open on router and works fine.

Do you have an idea of what it could be ?

Thanks a lot
Vic1743

**Comment by sebbu** [comment]
Hi, I have just checked the code. Unfortunately there is no logging in productive App, so we won't find out what is going wrong.

You could do some try & error tests. I have the following ideas:
- instead of using an explizit port, can you use the default port?
- instead of http, make use of (real) https. Maybe you should give Let’s Encrypt a try (do not work with self signed certificates because the app does not support your own CA).
- basic authentication should only be used with https.

As I do not know your knowledge of network configuration....
Do you really use your public IP of your providers router. If you are at home over wifi and the server is in the same network, it sounds like you are using your local IP (i.e. 192.168... or 10.10...).
But if it works on Safari over 3G (by name, not IP!).... it should work with the watch, too.

Does it work in the iControl Web App over 3G?
